### ISSUE TITLE
请阐述图中的关键要素和运行机制

### ISSUE THREAD

**Issue by meflyup** [DEIT2014/assignment#15]
![default](https://cloud.githubusercontent.com/assets/1710178/19255440/a7f6b1a2-8f90-11e6-95db-ff0f9d449fa8.png)

> 请用markdown格式撰写

**Comment by kyorakugjp** [comment]
＃＃关键要素:
客户，银行职员，取票机，排队号码，银行数据库。
＃＃运行机制:
客户通过取票机获取排队号码，银行职员根据号码顺序为客户提供服务，并对客户在银行的数据库进行修改。

**Comment by chiji1024** [comment]
##前端
简单的选择服务页面和ajax调用后端接口
##后端
每当有人申请服务时候将其加入相应的任务队列等待员工处理，并记录相关的信息。
处理完毕后将其放入备份回收表中，标记为以处理。

**Comment by suzy12345** [comment]
关键要素有取号机，银行职员，供银行职员使用的各种设备，广播，要办理业务的人。
运行机制是每个到银行办理业务的人都要先取号，然后等待，等到广播读到自己的号码时，去相应的窗口办理业务，办理完业务离开本窗口，本窗口闲置，开始接待下一位顾客。

**Comment by jenny19970204** [comment]
#银行运行机制：
1.取号 
2.排队（等候）
3.系统分配窗口
4.叫号
5.办理业务（执行）
#关键要素：
窗口分配 ：
所有窗口实时更新排队状况及分配任务

**Comment by ttzhang511** [comment]
- 每个客户有一个账户，存在银行的数据库里
- 当存款或取款时，职员间接将数据库中数据修改
- 客户通过取号排队办业务，取号机按顺序出号码

**Comment by shirleysr** [comment]
### 关键因素：

客户端（排号机），服务器端（柜员电脑），数据库端

### 运行机制：

顾客利用排号机取号或进行其他操作，银行柜员可以在其电脑上查看实时状态，进行修改。
客户端与服务器端实时通信连接，操作互动，并后台连接数据库记录数据

**Comment by DaBingXiaoQian** [comment]
#关键要素
排队情况，普通用户，银行工作人员，银行计算机系统，银行内部财产
#运行机制
先排队叫号，然后普通用户通过银行服务人员操作计算机系统进行交易，之后银行工作人员直接接触银行内部钱财，并与普通用户交易。

**Comment by cjLinda** [comment]
###关键要素：
银行职员、客户、取号机制、银行数据库系统
###运行机制：
客户通过取号机制，确定需完成业务的种类，完成数字信息排队，等待；
等广播报号时，去窗口办理业务，再给银行职员评分。
职员根据客户需求修改的信息，发送给银行数据库系统，向服务器发出请求，服务器同意，接受信息更新，等待下一次信息的处理申请

**Comment by lzhiwei** [comment]
关键要素:
取票机，号码，计算机，服务器
运行机制:
首先客户通过取票机发出取号命令，计算机会在已有号码的基础上加1并把号码输出，当前面以为客户的业务结束，银行职员通过计算机发出下一个的命令，计算机会往下执行一条语句，叫到下一个号码。银行职员在计算机中的操作会通过网络储存在服务器中。

**Comment by wqwtsr** [comment]
关键要素：业务办理 机器内部程序  人员 货币 运行及管理
运行机制：即时反馈机制 存取机制 服务流程机制 人机交互

**Comment by duqianner** [comment]
首先选择需办理的业务种类，系统输出排队号码，当收银员按下业务结束按钮时，4个柜台按照号码先后和时间先后次序依次显示号码，并实时变更正在等待的人次

**Comment by MiniTake** [comment]
关键要素：
服务窗口（工作人员），客户，排号系统，具体服务，数据库
运行机制：
多个服务窗口（多个银行工作人员）
一个排号系统
排号系统按顺序排号
服务窗口（工作人员）按照实时情况接受服务信息（排号）
工作人员根据客户选择服务类型 提供相应的服务
银行的数据库根据工作人员的操作 做出相应的改动

**Comment by icecreamtoo** [comment]
关键要素：
对象：用户，工作人员（经理，一般职员等）
设备：取号系统，在线服务系统
运机机制：
客户通过取号机获取号码，后台获取正在排队号码，按时间顺序报给正在工作的空闲的工作系统。
工作系统完成此次工作后，点击完成。
取号系统依次安排工作

**Comment by SunnyGiner** [comment]
## 类和对象

这张图比较类似于类和对象之间的关系，对象从类中调用方法和参数时，就类似像客户向银行取款。
或者客户端向服务器获取数据

**Comment by panchenyu** [comment]
###关键要素
排队取号机 
电子显示屏 
LED显示器 
语音系统 
互联网络
总服务器

###运行机制
用户从取号机上点击取号，取号机在现有队列末端加入新的号码，并向服务器主机发送信息；轮到某个号码时，通过终端确认此号码持有人正在接受服务，服务器主机发送信号，显示器及语音系统呼叫顺位第二的用户；此时新的挂号继续递进

**Comment by fireblue204** [comment]
关键要素：取票机，序号，银行数据库，银行职员
运行机制：客户通过取票机取得序号，取票机将客户序号传递到后端数据库队列中，数据库实时更新用户序号，职员对相应序号的客户服务

**Comment by critallu** [comment]
关键要素
1.办理业务的人：
2.挂号机：
3.银行工作人员：
4.钱/卡/存折等

运行机制：
1.需要办理业务的人走进大厅，利用身份证在挂号机那边挂号
2.根据号码排队，等待自己的号码被叫到
3.去对应的窗口办理业务
