### ISSUE TITLE
关于HttpRequest的问题

### ISSUE THREAD

**Issue by DaBingXiaoQian** [DEIT2014/assignment#21]
老师，在dart:html和dart:io这两个库中都包含HttpRequest，如果两个库都引用了，那使用HttpRequest的时候该怎么区分使用的是哪个？

**Comment by DaBingXiaoQian** [comment]
我发现好像在客户端的dart文件中只需要导入dart:html库，在服务器端的dart文件中只需要导入dart:io库，所以好像用HttpRequest并没有冲突，不确定是不是这样。

**Comment by meflyup** [comment]
你的发现很正确，如果你在web 客户端写，就用dart:html库中的；如果你要写一个独立的command line应用程序作为测试，那么就用dart:io来写。web中还能用dart:html;command line程序中只用dart:io.不能同时都用。
