### ISSUE TITLE
map 取值问题

### ISSUE THREAD

**Issue by icecreamtoo** [DEIT2014/assignment#25]
var gifts = {  
  "first" : "partridge",  
  "second": "turtledoves",  
  "fifth" : "golden rings"};  
gifts.forEach((k,v) => print('$k : $v')); 
老师，map取值，我不知道是哪一个。上面那个是打印出来所有的值了，是这个么？
我在官网上找了找，
Map<String, int> scores = {'Bob': 36};
for (var key in ['Bob', 'Rohan', 'Sophena']) {
  scores.putIfAbsent(key, () => key.length);
}
scores['Bob'];      // 36
scores['Rohan'];    //  5
scores['Sophena'];  //  7
是利用这个么？感觉官网上的程序里，值和值所代表的字符串位置是：“string”：“num”，我写的是反的，是错误的么？
然后，不知道到底map取值用哪一个方法

**Comment by meflyup** [comment]
你找到官网描述很好。取值用：号前面的作为健，你用的没错的。  至于：  

> 值和值所代表的字符串位置是：“string”：“num”，我写的是反的，是错误的么？   

你写的是反的是什么意思，这里都是正确的

**Comment by icecreamtoo** [comment]
在datajson文件中，我是“学号”：“姓名”的写法

**Comment by icecreamtoo** [comment]
最后改成这样了，但是运行不出来，不知道问题在哪里。π_π

onDataLoaded(responseText) {
  //print(" Data Loaded");//可以不要
  var jsonString;
  jsonString = responseText;//拿到数据
  Map jsonObject;
  jsonObject=JSON.decode(jsonString);

  var random=new Random();
  var num;
  num = random.nextInt(21);
  querySelector('#showme').text = "学生姓名："+jsonObject['callingDATA'][num+1.toString()];

}

**Comment by icecreamtoo** [comment]
``` dart
onDataLoaded(responseText) {//服务器返回的文本，在服务器里面有个桶，里面的东西，回调函数（直接写进去，就有这个数据了）
  //print(" Data Loaded");//可以不要
  var jsonString;
  jsonString = responseText;//拿到数据
  Map jsonObject;
  jsonObject=JSON.decode(jsonString);

  var random=new Random();//如果填上数字，那么一直显示一个随机数，现在每点击一下，就会显示不同的随机数；
  var num;
  num = random.nextInt(21);
  String i=(num+1).toString();
  var a=jsonObject["callingDATA"].toString();
  querySelector("#showme").text = jsonObject["callingDATA"][1].toString();
}

```

**Comment by icecreamtoo** [comment]
这是可以运行的，将取出来的数据变成字符串，显示出来
