### ISSUE TITLE
动态添加input标签

### ISSUE THREAD

**Issue by DaBingXiaoQian** [DEIT2014/assignment#32]
老师，我自己又尝试了一下动态插入input标签的问题。
1. 不能够动态循环加入input标签的原因是，代码中有 

> querySelector('#word$i').nextNode.text='$i';

这句话把input后面的node给占用了，所以就不能够动态加入。

2. 如果把
> querySelector('#word$i').nextNode.text='$i';

这句代码去掉就可以动态加入，但是加入的input 标签为"<input></input>"，形式像div标签，这不是正常的<input>标签。所以不能够正确在页面上显示出来，当然更不能够在后面加nextNode.text了。
![input3](https://cloud.githubusercontent.com/assets/22018510/21472039/c49fa298-cb02-11e6-99e2-2ba4e13de266.png)

所以，现在的问题有两个：
1. 动态加入div的append方法不适合input标签，因为"<div></div>"是正确的形式，但是"<input></input>"是不正确的形式。所以不知道要用怎样的动态加入input 方法。
2.怎样加入input标签后面的文字，如果继续使用nextNode.text的话，那么就不能在input标签后面动态加入input标签，因为已经被文字给占了。

以下链接为相关代码链接：https://github.com/DaBingXiaoQian/inputAdd

**Comment by meflyup** [comment]
这个问题在于：
input element不是一个容器，不能往里面在添加其他的element了。如果要添加得选择容器比如div之类的标签。你的代码：  
```
var onInputold=document.getElementById("word$i");
var onInputnew=document.createElement("input");
...
onInputold.append(onInputnew);
```
就是尝试在第一个input（onINputold）中又在加一个input，是不行的。

**Comment by meflyup** [comment]
另外，往容器添element建议采纳[最佳实践方案](https://webdev.dartlang.org/tutorials/low-level-html/add-elements)
